d/{rules, defaultconf.postinst}: adjust permissions of keylime.conf
utkarsh2102/python-keylime pull request #39
Opened 2022-01-20 16:01 UTC by THS-on

The keylime.conf should only be readable by the keylime user.
The keylime.conf might contain passwords that a normal user should not be able to read.

Upstream change: https://github.com/keylime/keylime/pull/844

2022-01-20 16:06 UTC, utkarsh2102 reviewed
Hey,

Thank you very much for this! Downgrading permissions to 600 looks good to me, makes sense. However, I want to know if we really need a new .postinst file? We have `python3-keylime.postinst.in` that we could re-use, I think. I don't know why'd we need another one here?

2022-01-20 16:08 UTC, THS-on commented
The other postinst files have special handling for cleanup and creation of `/var/lib/keylime` which we don't need for the config.

2022-01-25 08:31 UTC, cpaelzer requested changes
Hi,
generally ok but had to suggest a changes and discussions to be had.

2022-01-25 08:31 UTC, cpaelzer commented on debian/python3-keylime-defaultconf.postinst
> +    fi
I'm a fan of using the postinst of the package that owns the file for this fixup (below).

But, the group/user checks above are duplication which is never good.
Gladly the other place where this is done is `python3-keylime` and since `python3-keylime` -DEPENDS-> `python3-keylime-defaultconf` we can safely assume that the postinst of `python3-keylime-defaultconf` has run before that of `python3-keylime`.

Therefore I'd suggest to not only add these user/group things here, but at the same time remove it from the postinst of `python3-keylime`.

2022-01-25 08:31 UTC, cpaelzer commented on debian/python3-keylime-defaultconf.postinst
> +        chmod 600 /etc/keylime.conf
Changing the permission/ownership of a file in a package (the `d/rules` change) is fine as it allows the admin to use [dpkg-statoverride](https://manpages.debian.org/unstable/dpkg/dpkg-statoverride.1.html) to force over that without every update killing his/her decision.

That deficiency isn't new - our current code in `debian/python3-keylime.postinst.in` is affected by the same.
We could server the user better if we guard all those (the new and the old chmod/chown calls) by e.g. `dpkg-statoverride --list /etc/keylime.conf > /dev/null` on RC=0 there is an override in place and we do not want to mess with it.

This has [examples](https://codesearch.debian.net/search?q=dpkg-statoverride&literal=1) then using chown/chmod or even directly statoverride to set those.
Unless OTOH we say "no, having exactly these permissions is the one and only true config, admins are not allowed to mess with it". In that case leave the chown/chmod.

2022-01-25 08:31 UTC, cpaelzer commented on debian/rules
> +	install -D -m 0600 keylime.conf debian/python3-keylime-doc/usr/share/doc/keylime/keylime.conf.example
I'm not convinced on 0600 the example file.
`$ find  /usr/share/doc/ -perm 0600` tells me this would be a first of its kind which most of the times means _wrong_.

I'd suggest keeping the example 644 (also your postinst didn't update the examples permission, we'd need to go all the way on either decision)

2022-01-25 08:41 UTC, THS-on commented on debian/python3-keylime-defaultconf.postinst
> +    fi
The issue is that the `python3-keylime-server` and `python3-keylime-agent` packages only recommend `python3-keylime-defaultconf`, so we cannot actually remove the user/group checks from the other postinst files.

https://github.com/utkarsh2102/python-keylime/blob/5c3da7fc243b7b51387142b45b870ac921a3ed41/debian/control#L77

2022-01-25 08:42 UTC, THS-on commented on debian/python3-keylime-defaultconf.postinst
> +        chmod 600 /etc/keylime.conf
Allowing the admin to at least change the group could make sense, so I'll have a closer look at the examples.

2022-01-25 08:45 UTC, THS-on commented on debian/rules
> +	install -D -m 0600 keylime.conf debian/python3-keylime-doc/usr/share/doc/keylime/keylime.conf.example
Yeah I can change that back.

I can change that also back from 600 to 644 for the `/etc/keylime.conf` because the packaging in Debian "fixes" it by changing back automatically to 644.

2022-01-25 09:22 UTC, THS-on commented on debian/python3-keylime-defaultconf.postinst
> +        chmod 600 /etc/keylime.conf
fixed

2022-01-25 09:22 UTC, THS-on commented on debian/rules
> +	install -D -m 0600 keylime.conf debian/python3-keylime-doc/usr/share/doc/keylime/keylime.conf.example
fixed

2022-01-25 09:22 UTC, cpaelzer commented on debian/python3-keylime-defaultconf.postinst
> +    fi
But they need the user/group to exist, right ...
How about at least putting that shred code in an `debian/common.postinst.in` or similar and including it on pkg-build time into both active postinst files? That way at least we avoid the duplication which surely will make us fail by adapting one but not the other down the road.

2022-01-25 09:56 UTC, THS-on commented on debian/python3-keylime-defaultconf.postinst
> +    fi
Good idea. I've done that now.

2022-01-25 10:24 UTC, cpaelzer commented on debian/rules
> +	sed -i -e '/#KEYLIME_COMMON#/ r debian/common.postinst.in' -e /#KEYLIME_COMMON#/d debian/python3-keylime-agent.postinst
debian/python3-keylime-defaultconf.postinst.in debian/python3-keylime.postinst.in instead of debian/python3-keylime-server.postinst debian/python3-keylime-agent.postinst ?

2022-01-25 10:25 UTC, cpaelzer commented on debian/python3-keylime.postinst.in
> +#DEBHELPER#
Was the drop of that final newline intentional?

2022-01-25 15:29 UTC, THS-on commented on debian/python3-keylime.postinst.in
> +#DEBHELPER#
No, thanks for catching that.

2022-01-25 15:29 UTC, THS-on commented on debian/rules
> +	sed -i -e '/#KEYLIME_COMMON#/ r debian/common.postinst.in' -e /#KEYLIME_COMMON#/d debian/python3-keylime-agent.postinst
Is now simplified.

2022-01-28 16:08 UTC, cpaelzer approved these changes
Thanks! I didn't have time to re-review in depth, but all I formerly found is resolved.
+1

2022-01-28 17:45 UTC, merged

2022-01-28 17:45 UTC, utkarsh2102 commented
Thank you, Thore. I'll review the other PR tomorrow. \o/