WIP: Seperating the agent from the server components
utkarsh2102/python-keylime pull request #4
Opened 2021-06-11 10:36 UTC by THS-on

This is my first attempt at separating the agent  from the server components. 
A real separation is not really possible because Keylime does not split agent and other components cleanly.

I've run into the issue that `pybuild` overrides the `DESTDIR` if it is set to `debian/tmp/` with the package name. 
This makes splitting the package into multiple packages harder and the current workaround does not play nice with `dh-exec`.

Do you have any idea how to solve this?

2021-06-23 21:35 UTC, utkarsh2102 commented
> This is my first attempt at separating the agent from the server components.

Lovely! Thank you for this! 🎉 

> The verifier and registrar do not need root privileges to fully function correct?

Yep, both of them don't need to be root. The recent commits in keylime makes agent run as non-root, too! But that is not yet released!

2021-06-24 08:49 UTC, THS-on commented
I've now added that the verifier and registrar don't run as root. 

Currently there is a race condition between the registrar and verifier on first startup when the verifier has not yet generated it the CA and the certificates. Maybe we should add an `After=keylime_verifier.service`  to the `keylime_registrar.service`.
```
Jun 24 10:30:15 test-system keylime_registrar[7666]: 2021-06-24 10:30:15.939 - keylime.cloudverifier_common - INFO - Setting up TLS...
Jun 24 10:30:15 test-system keylime_registrar[7666]: Traceback (most recent call last):
Jun 24 10:30:15 test-system keylime_registrar[7666]:   File "/usr/bin/keylime_registrar", line 33, in <module>
Jun 24 10:30:15 test-system keylime_registrar[7666]:     sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_registrar')())
Jun 24 10:30:15 test-system keylime_registrar[7666]:   File "/usr/lib/python3/dist-packages/keylime/cmd/registrar.py", line 21, in main
Jun 24 10:30:15 test-system keylime_registrar[7666]:     registrar_common.start(
Jun 24 10:30:15 test-system keylime_registrar[7666]:   File "/usr/lib/python3/dist-packages/keylime/registrar_common.py", line 448, in start
Jun 24 10:30:15 test-system keylime_registrar[7666]:     context = cloud_verifier_common.init_mtls(section='registrar',
Jun 24 10:30:15 test-system keylime_registrar[7666]:   File "/usr/lib/python3/dist-packages/keylime/cloud_verifier_common.py", line 80, in init_mtls
Jun 24 10:30:15 test-system keylime_registrar[7666]:     raise Exception(
Jun 24 10:30:15 test-system keylime_registrar[7666]: Exception: It appears that the verifier has not yet created a CA and certificates, please run the verifier first
Jun 24 10:30:16 test-system systemd[1]: keylime_registrar.service: Main process exited, code=exited, status=1/FAILURE
```

2021-06-24 09:30 UTC, utkarsh2102 commented
Hey,

> Currently there is a race condition between the registrar and verifier on first startup when the verifier has not yet generated it the CA and the certificates. Maybe we should add an After=keylime_verifier.service to the keylime_registrar.service.

Yep, I noticed that but it resolves in about ~120s when it does a restart (cf: `Restart=on-failure`). Adding that `After` as you suggested didn't really work when I tried, does it work for you?

2021-06-24 11:41 UTC, THS-on commented
> Adding that After as you suggested didn't really work when I tried, does it work for you?

I thought it worked but I have tested it now on a clean installation and you are correct it doesn't work.
Your solution to just restart the service is the best I can currently think of. We could wait for the necessary files being created but this would break if some people don't use the default configuration.

The current state of the PR seems to work but I'll test it more next week in my test environment.

2021-07-05 14:47 UTC, THS-on commented
@utkarsh2102 I haven't found any issues during testing. It would be nice if you can have a look at it and see if the current implementation works for you.

2021-07-22 20:07 UTC, THS-on commented
@utkarsh2102 Now that v6.1.1 is released should I implement the non root feature in this PR or do you want to update first?

2021-07-23 03:29 UTC, utkarsh2102 commented
Hi @THS-on,

> @utkarsh2102 Now that v6.1.1 is released should I implement the non root feature in this PR or do you want to update first?

I've pushed the updated package, that is, v6.1.1. I've also reverted the condition and the keylime_agent should now run as non-root, hopefully. Can you test this version?

Whilst installing this in Ubuntu Bionic (18.04), I found this error:
`Jul 22 21:50:12 tpm2 keylime_registrar[690]: ModuleNotFoundError: No module named 'dataclasses'`
...and this makes me a bit skeptical as to what's happening. I understand `dataclasses` is already in-build in Python 3.7+ but we have Python 3.6.9 in Ubuntu Bionic. However, I did `pip3 install dataclasses` and that installed the module however restarting the service still fails the same way. Any clue!? 😞

2021-07-23 21:05 UTC, THS-on commented
I've now updated my PR to make the agent work without root. I've tested that on Debian 11 and it seems to work but I'll test it more next week.

For the Ubuntu Bionic error: Is the package installed globally (sudo -H pip3 install dataclasses)?

2021-08-10 19:07 UTC, utkarsh2102 commented
Awesome, thank you, @THS-on! 🎉 

This looks excellent. I wanted to know if you could test the new commits I pushed, which you rebased upon? And also let me know which Ubuntu release did you test this on? I'll begin testing your branch tomorrow onward and will merge in the next few days and roll out a release.

Please let me know if you've got any questions or concerns. That said, thank you so much for all your work and help on this! 🌮

2021-08-10 19:24 UTC, THS-on commented
Thanks for looking at it @utkarsh2102. 

I've now build the package with your new changes included and only found something with your dataclasses patch https://github.com/utkarsh2102/python-keylime/issues/6#issuecomment-896250403. Otherwise it seems to work as intended.
I'm currently testing on Debian 11 with a custom kernel. If you want I can also test it on a Ubuntu version.

2021-08-11 00:15 UTC, utkarsh2102 commented
Hello @THS-on 👋🏻 

> I've now build the package with your new changes included and only found something with your dataclasses patch [#6 (comment)](https://github.com/utkarsh2102/python-keylime/issues/6#issuecomment-896250403). Otherwise it seems to work as intended.

Great, with #10 being merged, this is fixed! Thank you for doing that! 🎉 

> I'm currently testing on Debian 11 with a custom kernel. If you want I can also test it on a Ubuntu version.

Sweet, I'd like to know if you can test this on Ubuntu 18.04 and Ubuntu 20.04, if time permits? No problem if you can't but would be really helpful if you can do that! \o/

2021-08-11 09:05 UTC, THS-on commented
For Ubuntu 18.04 there are some packages missing that are specified also in the original control file: tpm2-abrmd, libtss2-dev, python3-m2crypto, tpm-udev. Do you have a custom repository for 18.04 because I couldn't find those packages in the backports repo.

Ubuntu 20.04 seems to work mostly fine. Measured boot log is broken because the command `tpm2_eventlog` is missing in the tpm2-tools version shipped in 20.04.

2021-08-11 12:36 UTC, utkarsh2102 commented
Hi @THS-on,

> For Ubuntu 18.04 there are some packages missing that are specified also in the original control file: tpm2-abrmd, libtss2-dev, python3-m2crypto, tpm-udev. Do you have a custom repository for 18.04 because I couldn't find those packages in the backports repo.

Ugh, this is awfully stupid of me. Sorry for not mentioning this earlier. Here's the PPA for 18.04: https://launchpad.net/~utkarsh/+archive/ubuntu/keylime.

Use this as:
```
sudo add-apt-repository ppa:utkarsh/keylime
sudo apt-get update
sudo apt-get install tpm2-abrmd libtss2-dev python3-m2crypto tpm-udev tpm2-tools
```

These are new versions of tpm2 stack and things should work fine, please let me know if it doesn't. Of course, don't use the keylime package from the PPA itself :)

> Ubuntu 20.04 seems to work mostly fine. Measured boot log is broken because the command `tpm2_eventlog` is missing in the tpm2-tools version shipped in 20.04.

Great, thanks for letting me know. This is expected and isn't a problem in our python-keylime package itself. Just let me know how things work on 18.04. TIA! \o/

2021-08-11 13:57 UTC, utkarsh2102 commented
Hey again,

Whilst testing your branch, I installed python3-keylime and python3-keylime-server and everything was fine! Yay!
However, then I purged python3-keylime-server and installed python3-keylime-agent and the service failed, and here are the logs:

```
Aug 11 13:55:03 tpm2 systemd[1]: Reloading.
Aug 11 13:55:03 tpm2 systemd[1]: /lib/systemd/system/keylime_agent.service:14: Executable path is not absolute, ignoring: -+chown -hHR keylime:tss /sys/kernel/security/tpm0
Aug 11 13:55:03 tpm2 systemd[1]: /lib/systemd/system/keylime_agent.service:15: Executable path is not absolute, ignoring: -+chown -hHR keylime:tss /sys/kernel/security/ima
Aug 11 13:55:03 tpm2 systemd[1]: Reloading.
Aug 11 13:55:03 tpm2 keylime_agent[1964]: Using config file /etc/keylime-agent.conf
Aug 11 13:55:03 tpm2 keylime_agent[1964]: 2021-08-11 13:55:03.734 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.1.1
Aug 11 13:55:03 tpm2 keylime_agent[1964]: 2021-08-11 13:55:03.808 - keylime.cloudagent - WARNING - Measurement list path /sys/kernel/security/tpm0/binary_bios_measurements not accessi
Aug 11 13:55:03 tpm2 keylime_agent[1964]: 2021-08-11 13:55:03.832 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.1.1
Aug 11 13:55:03 tpm2 keylime_agent[1964]: 2021-08-11 13:55:03.840 - keylime.secure_mount - INFO - mounting secure storage location /var/lib/keylime/secure on tmpfs
Aug 11 13:55:03 tpm2 keylime_agent[1964]: Traceback (most recent call last):
Aug 11 13:55:03 tpm2 keylime_agent[1964]:   File "/usr/bin/keylime_agent", line 11, in <module>
Aug 11 13:55:03 tpm2 keylime_agent[1964]:     load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
Aug 11 13:55:03 tpm2 keylime_agent[1964]:   File "/usr/lib/python3/dist-packages/keylime/cmd/agent.py", line 15, in main
Aug 11 13:55:03 tpm2 keylime_agent[1964]:     keylime_agent.main()
Aug 11 13:55:03 tpm2 keylime_agent[1964]:   File "/usr/lib/python3/dist-packages/keylime/keylime_agent.py", line 483, in main
Aug 11 13:55:03 tpm2 keylime_agent[1964]:     secdir = secure_mount.mount()
Aug 11 13:55:03 tpm2 keylime_agent[1964]:   File "/usr/lib/python3/dist-packages/keylime/secure_mount.py", line 57, in mount
Aug 11 13:55:03 tpm2 keylime_agent[1964]:     cmd_exec.run(cmd)
Aug 11 13:55:03 tpm2 keylime_agent[1964]:   File "/usr/lib/python3/dist-packages/keylime/cmd_exec.py", line 41, in run
Aug 11 13:55:03 tpm2 keylime_agent[1964]:     (cmd, code, expectedcode, retout_list, reterr_list))
Aug 11 13:55:03 tpm2 keylime_agent[1964]: Exception: Command: ('mount', '-t', 'tmpfs', '-o', 'size=1m,mode=0700', 'tmpfs', '/var/lib/keylime/secure') returned 1, expected 0, output []
Aug 11 13:55:04 tpm2 systemd[1]: /lib/systemd/system/keylime_agent.service:14: Executable path is not absolute, ignoring: -+chown -hHR keylime:tss /sys/kernel/security/tpm0
Aug 11 13:55:04 tpm2 systemd[1]: /lib/systemd/system/keylime_agent.service:15: Executable path is not absolute, ignoring: -+chown -hHR keylime:tss /sys/kernel/security/ima
Aug 11 13:55:04 tpm2 systemd[1]: keylime_agent.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 13:55:04 tpm2 systemd[1]: keylime_agent.service: Failed with result 'exit-code'.
```

2021-08-11 14:00 UTC, utkarsh2102 commented
And then restarting the `keylime_agent` service, it ran for a sec and failed again:
```
root@tpm2:/home/utkarsh/keylime/python-keylime# systemctl status keylime_agent
● keylime_agent.service - The Keylime compute agent
   Loaded: loaded (/lib/systemd/system/keylime_agent.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/system/keylime_agent.service.d
           └─zzz-lxc-service.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-08-11 13:58:13 UTC; 2s ago
  Process: 2490 ExecStart=/usr/bin/keylime_agent (code=exited, status=1/FAILURE)
 Main PID: 2490 (code=exited, status=1/FAILURE)

Aug 11 13:58:13 tpm2 systemd[1]: keylime_agent.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 13:58:13 tpm2 systemd[1]: keylime_agent.service: Failed with result 'exit-code'.
root@tpm2:/home/utkarsh/keylime/python-keylime# journalctl -xe
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     conn = self._new_conn()
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     self, "Failed to establish a new connection: %s" % e)
Aug 11 13:58:13 tpm2 keylime_agent[2490]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd99cfc1e80>: Failed to establish a new connection: [E
Aug 11 13:58:13 tpm2 keylime_agent[2490]: During handling of the above exception, another exception occurred:
Aug 11 13:58:13 tpm2 keylime_agent[2490]: Traceback (most recent call last):
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     timeout=timeout
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     _stacktrace=sys.exc_info()[2])
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Aug 11 13:58:13 tpm2 keylime_agent[2490]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8890): Max retries exceeded with url: /agents/D432FBB3-D2F1-4A97-
Aug 11 13:58:13 tpm2 keylime_agent[2490]: During handling of the above exception, another exception occurred:
Aug 11 13:58:13 tpm2 keylime_agent[2490]: Traceback (most recent call last):
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/keylime/registrar_client.py", line 139, in doRegisterAgent
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     response = client.post(f'/agents/{agent_id}', cert=tls_cert_info, data=json.dumps(data), verify=False)
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/keylime/requests_client.py", line 32, in post
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     return self.session.post(self.base_url + url, **kwargs)
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 567, in post
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     return self.request('POST', url, data=data, json=json, **kwargs)
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     resp = self.send(prep, **send_kwargs)
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     r = adapter.send(request, **kwargs)
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     raise ConnectionError(e, request=request)
Aug 11 13:58:13 tpm2 keylime_agent[2490]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8890): Max retries exceeded with url: /agents/D432FBB3-D2F1-4A
Aug 11 13:58:13 tpm2 keylime_agent[2490]: Traceback (most recent call last):
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/bin/keylime_agent", line 11, in <module>
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_agent')()
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/keylime/cmd/agent.py", line 15, in main
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     keylime_agent.main()
Aug 11 13:58:13 tpm2 keylime_agent[2490]:   File "/usr/lib/python3/dist-packages/keylime/keylime_agent.py", line 540, in main
Aug 11 13:58:13 tpm2 keylime_agent[2490]:     raise Exception("Registration failed")
Aug 11 13:58:13 tpm2 keylime_agent[2490]: Exception: Registration failed
Aug 11 13:58:13 tpm2 systemd[1]: keylime_agent.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 13:58:13 tpm2 systemd[1]: keylime_agent.service: Failed with result 'exit-code'.
```

Looks like I am missing something, how are you testing and running the agent? With all the three packages installed, that is, registrar, verifier, and the agent so that agent doesn't throw a "registration failed" exception or something?

2021-08-11 14:04 UTC, THS-on commented
> Looks like I am missing something, how are you testing and running the agent? With all the three packages installed, that is, registrar, verifier, and the agent so that agent doesn't throw a "registration failed" exception or something?

Do you have the Keylime registrar service running? It looks like the agent cannot connect to it. I've one VM running the Keylime registrar and verifier and another one that is only running the agent.

2021-08-11 14:06 UTC, THS-on commented on debian/python3-keylime-server.postrm
> +    rm -rf $KEYLIME_DIR
@utkarsh2102 purging the server currently removes also all potential agent files. I don't know if there is a good way to differentiate between agent and sever files in this directory.

2021-08-11 15:05 UTC, utkarsh2102 commented
Hey,

> I cannot install the packages from your ppa.

Sorry, again. Things should be fine now. Please re-test and let me know. Sorry for the trouble and thanks for your help! \o/

2021-08-11 15:06 UTC, utkarsh2102 commented
> > Looks like I am missing something, how are you testing and running the agent? With all the three packages installed, that is, registrar, verifier, and the agent so that agent doesn't throw a "registration failed" exception or something?
> 
> Do you have the Keylime registrar service running? It looks like the agent cannot connect to it. I've one VM running the Keylime registrar and verifier and another one that is only running the agent.

I see. I am interested in seeing and knowing how you connect the two VMs for making the agent connect to the registrar (and the verifier)? 😅

2021-08-17 11:31 UTC, cpaelzer requested changes
Utkarsh asked me to have a look as I was a fan of splitting the daemons.
This already is great work, but IMHO needs some cleanup and splitting in addition to the tests that you and utkarsh already do.

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime-agent.install
> +etc/keylime.conf => /etc/keylime-agent.conf
This does a lot in one commit,  some splitting would help readability.
For example the addition of /etc/keylime-agent.conf  and the related change to Environment in the .service file could go in an extra commit.

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime-agent.postinst
> +    # We set here the keylime user as owner because otherwise
^^ Trailing Whitespace

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime-agent.install
> +etc/keylime.conf => /etc/keylime-agent.conf
In the same way setting Group/User in .service files in python3-keylime-server.keylime_registrar.service /  python3-keylime-server.keylime_verifier.service and the related chown to tpm0/ima in python3-keylime-agent.keylime_agent.service should IMHO be one if not two separate commits.

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime-server.postinst
> +
We got two almost identical postinst files due to this which yell "bad to maintain" at me.
And to prove they already have different whitespacing at the chown line as well as one having an explanatory comment while the other misses it. The only individual bit here seems to be the log-dir which only the server needs.
Everything else here seems shared.

I'd ask to create this as either generated files (one source generating two .postinst on build) or by using a helper file that you source). Either way all the code for creating users should live only once in the source.

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime-server.postinst
> +
The same applies to postrm to some extend, please unify that as well.

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime-server.postrm
> +    rm -rf $KEYLIME_DIR
This needs to become "the last one that leaves cleans" so you'd have to check for the sibling packages if they are still installed. To `rm -rf` a dir still used by the remaining package seems wrong.

The problem is that doing so with dpkg means might end up in locking issues, so most likely you'll need some helper like a stamp file. How about every purge dropping a $pkg.purged file in those directories.
And then (all postinsts) would check and if ALL the expected .purged files are present delete the directory.

Note: On install the postinst would want to remove the respective $pkg.purged file.

2021-08-17 11:31 UTC, cpaelzer commented on debian/python3-keylime.install
> +keylime/static usr/lib/python3/dist-packages/keylime
I think this is right, but should again be a separate commit

2021-08-17 11:31 UTC, cpaelzer commented on debian/rules
> +export PYBUILD_DESTDIR=debian/tmp
PYBUILD changes also are a commit (and always on all of them thereby also an extra explanation why/what is going on)

2021-08-17 13:54 UTC, utkarsh2102 commented
Hi @THS-on,

If you can take a look at @cpaelzer's suggestions (and adapt to them), that'd be perfect and I can merge this right away and make a release soon. What do you think?

TIA! \o/

2021-08-17 15:12 UTC, THS-on commented
@utkarsh2102 sounds like a good plan. I'll look at the suggestions later today and modify my PR accordingly.

2021-08-17 17:56 UTC, THS-on commented on debian/rules
> +export PYBUILD_DESTDIR=debian/tmp
I've added the reason we change that to the commit.

2021-08-17 17:56 UTC, THS-on commented on debian/python3-keylime.install
> +keylime/static usr/lib/python3/dist-packages/keylime
done

2021-08-17 17:57 UTC, THS-on commented on debian/python3-keylime-agent.install
> +etc/keylime.conf => /etc/keylime-agent.conf
Those are now split into their own commits.

2021-08-17 17:57 UTC, THS-on commented on debian/python3-keylime-server.postinst
> +
done

2021-08-17 17:59 UTC, THS-on commented on debian/python3-keylime-server.postrm
> +    rm -rf $KEYLIME_DIR
The new packages will create a "$pkg.installed" file and the postrm checks if there is no such file before removing the whole /var/lib/keylime directory.

2021-08-17 18:04 UTC, THS-on commented
@cpaelzer can you look at my changes? All your suggestions are now implemented.

@utkarsh2102 Can retest if the packages are created correctly on your system and purging is working as intended?

2021-08-18 08:41 UTC, cpaelzer approved these changes
Awesome, thanks for the updates this feels like 99% there now.
I have one reasonable question and two nit-pick FYIs - see the comment below.

While I'd appreciate fixing those, even if not implemented I think this is now good - so if the testing of you and @utkarsh2102 is fine you'll have my approval.

2021-08-18 08:41 UTC, cpaelzer commented on debian/python3-keylime.keylime_registrar.service
> -Environment=TPM2TOOLS_TCTI=device:/dev/tpmrm0
Could the commit message explain why the user/group change makes the Environment variable obsolete?
Is it just because you only actually need it in the agent (there it stays) or is there more meaning to it?

If not related to the user change - again maybe an extra commit would be better.

P.S. in the commit message maybe "There is no need to run them as root anymore since v6.1."?
P.P.S. the commit message of f05acb0d274a9ce95276575c4bce77c437f92bd0 has "writtin in rust" -> "written in rust"

2021-08-18 13:59 UTC, THS-on commented on debian/python3-keylime.keylime_registrar.service
> -Environment=TPM2TOOLS_TCTI=device:/dev/tpmrm0
This environment variable is not needed for those services, but indeed has nothing to do with the commit so I made an extra commit.

> P.S. in the commit message maybe "There is no need to run them as root anymore since v6.1."?

It should be also possible to run the registrar and verifier as non root before v6.1. The agent now run only since v6.1 as non root.

>  P.P.S. the commit message of f05acb0 has "writtin in rust" -> "written in rust"

Fixed.

2021-08-18 14:03 UTC, utkarsh2102 commented
Hi @THS-on,

Thank you for resolving everything @cpaelzer raised. I'll test this branch (with new changes) tomorrow once and merge them. Thanks, once again, for all your work! 🎉

2021-08-19 14:08 UTC, utkarsh2102 approved these changes
> * Now because our agent uses the default id we can just do: ` keylime_tenant -c add -f secret`

Okay, probably I am missing and messing up something, that's why I get:
`keylime.tenant.UserError: The contact ip address for the agent was not specified.`
and simultaneously:
`OSError: Could not find the TLS certificate file, invalid path: /var/lib/keylime/cv_ca/client-cert.crt`

But I guess that's unrelated to this. Let me know if you know what is it, but all good here. Thanks for working on this! 🎉

2021-08-19 14:08 UTC, merged

2021-08-19 14:15 UTC, utkarsh2102 commented
> `OSError: Could not find the TLS certificate file, invalid path: /var/lib/keylime/cv_ca/client-cert.crt`

Aaaaaaah. Wrong permissions!?
```
utkarsh@tpm2:~/keylime$ ls /var/lib/keylime/cv_ca/
ls: cannot open directory '/var/lib/keylime/cv_ca/': Permission denied
utkarsh@tpm2:~/keylime$ sudo ls /var/lib/keylime/cv_ca/
[sudo] password for utkarsh: 
cacert.crt  cacrl.pem	   client-cert.crt     client-public.pem  tpm2-cert.crt     tpm2-public.pem
cacrl.der   ca-public.pem  client-private.pem  private.yml	  tpm2-private.pem
```

D'oh!?