Changes for 6.3.1
utkarsh2102/python-keylime pull request #42
Opened 2022-02-22 12:43 UTC by THS-on

Changes were tested on Debian 11, Ubuntu 20.4 (Focal) and Ubuntu 18.04 (Bionic).

On 18.04 the verifier event loop still doesn't start (https://github.com/utkarsh2102/python-keylime/issues/11), but this has nothing to do with the update to 6.3.1.

2022-03-07 14:08 UTC, THS-on commented
@utkarsh2102 can you have a look at this PR?

2022-03-18 17:23 UTC, utkarsh2102 commented
Hey, please give me a few more days to review and merge this. Thank you! \o/

2022-04-06 19:37 UTC, THS-on commented
@utkarsh2102 now with 6.3.2 released, should I change this PR to target 6.3.2 or do you want to review the changes for 6.3.1 first and I make a followup PR for 6.3.2?

2022-04-06 19:43 UTC, utkarsh2102 requested changes
Hellu,

Sorry for the delay, review is done. Please address these and I'll merge this right away and then let's work on the new release separately. Let me know if you have any questions or concerns.

2022-04-06 19:43 UTC, utkarsh2102 commented on debian/changelog
> +keylime (6.3.1-1) unstable; urgency=medium
Change this to UNRELEASED, please? :D

2022-04-06 19:43 UTC, utkarsh2102 commented on debian/changelog
> +  [ Thore Sommer ]
No need for this since you're the only contributor for this release. :D

2022-04-06 19:43 UTC, utkarsh2102 commented on debian/patches/series
> +# embed-dataclasses-module.patch
Let's drop the patch then? :)

2022-04-06 19:43 UTC, utkarsh2102 commented on debian/python3-keylime-server.dirs
> +
Empty line ✂️

2022-04-06 19:43 UTC, utkarsh2102 commented on debian/python3-keylime-server.install
> -usr/bin/keylime_provider_vtpm_add
I assume this is no longer provided?

2022-04-06 19:53 UTC, THS-on commented on debian/python3-keylime-server.install
> -usr/bin/keylime_provider_vtpm_add
Yes, they were no longer useful and removed in upstream

2022-04-06 19:59 UTC, THS-on commented on debian/changelog
> +  [ Thore Sommer ]
done

2022-04-06 20:00 UTC, THS-on commented on debian/changelog
> +keylime (6.3.1-1) unstable; urgency=medium
done

2022-04-06 20:00 UTC, THS-on commented on debian/patches/series
> +# embed-dataclasses-module.patch
done

2022-04-06 20:00 UTC, THS-on commented on debian/python3-keylime-server.dirs
> +
done

2022-04-06 22:28 UTC, utkarsh2102 commented
Thank you! \o/

2022-04-06 22:28 UTC, merged

2022-04-06 22:28 UTC, utkarsh2102 commented
I wonder if you can please create a branch in your fork, please? :D

2022-04-07 07:23 UTC, THS-on commented
> I wonder if you can please create a branch in your fork, please? :D

I can do that. Should I still push the upstream import directly to this repo?